import './globals.css'
import { Inter } from 'next/font/google'

import HeaderComponent from './shared/components/HeaderComponent'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Mercado Libre',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/imagenes/icon.png" sizes="any" />
      </head>
      <body className={inter.className}>
        <HeaderComponent/>
        <main className=' mx-auto ' >
          {children}
        </main>
        
        </body>
    </html>
  )
}